---
systemProperties:
  # Additional system properties (http://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html) to load at
  # application startup (see http://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html for useful ones)

  http.proxyHost:          &httpProxyHost # <value>
  http.proxyPort:          &httpProxyPort # <value>
  http.nonProxyHosts:      #localhost|localhost.localdomain|127.0.0.1
  http.proxyUser:          &httpProxyUser # <value>
  http.proxyPassword:      &httpProxyPass # <value>

  #https.proxyHost:         *httpProxyHost
  #https.proxyPort:         *httpProxyPort
  #https.proxyUser:         *httpProxyUser
  #https.proxyPassword:     *httpProxyPass

  #socksProxyHost:          *httpProxyHost
  #socksProxyPort:          *httpProxyPort
  #java.net.socks.username: *httpProxyUser
  #java.net.socks.password: *httpProxyPass

defaultAuthenticator:
  #username: *httpProxyUser
  #password: *httpProxyPass
